dakash98/PadhaiPlanet-Frontend

package-lock.json, package.json
=> Adding react-router-dom

src/App.js, src/Components/Body.js, src/Components/Contentscreen.js, src/Components/Fetchdata.js, src/Components/Historypapers.js
1. Add fetch data functionality.
2. Integrate the values with the code.
=> Integration through API for Home_Page

package-lock.json, package.json, src/Components/Body.js, src/Components/Historypapers.js
1. Add login functionality.
2. Open and show pdf in content screen.
=> Added login post method and pdf opens in content-screen

src/Components/Historypapers.js
=> Required format of key completed

package-lock.json, package.json, src/App.js, src/Components/Body.js, src/Global.js, src/Papers/Historypapers.js
1. Dynamic code added for Historypapers page.
2. Created an object to navigate to pages for question papers.
=> Make code dynamic

src/App.js, src/Components/Body.js, src/Components/Exploremore.js, src/Global.js, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
Add login functionality.
Add toggle button for sign up and login.
Create page for each subject and do mapping according to convention.
Create page the most dynamic approach possible for now.
=> Add: Pages for each question paper, signin and signup toggle button

src/Components/Homepage.js, src/Papers/Historypapers.js
Sort blogs page navigation issue.
Keep user as not logged in for history page for testing login ad sign up page.
=> Resolve: blogs page navigation issue

src/Components/AboutUs.js, src/Components/Blogs.js, src/Components/Breadcrumbs.js, src/Components/Homepage.js, src/Components/Loginpage.js, src/Components/Navbar.js, src/Components/Profilepage.js, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
1. Make Login page global.
2. Make Navbar global.
3. Still need to work on CSS at some places.
=> Make Navbar and Login page global

src/Components/AboutUs.js, src/Components/Blogs.js, src/Components/Breadcrumbs.js, src/Components/Contentscreen.js, src/Components/Footer.js, src/Components/Homepage.js, src/Components/Navbar.js, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
Make Content screen global.
Add cross icon with functionality.
Correct Breadcrumb CSS.
=> Content screen global

package-lock.json, src/Components/Breadcrumbs.js, src/Components/Exploremore.js, src/Components/Loader.js, src/Components/Navbar.js, src/Papers/Englishpapers.js
1. Update contact us breadcrumb.
2. Add loader.
=> Update: contact us; Add: Loader

src/App.js, src/Components/Loader.js, src/Components/Navbar.js, src/Global.js, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
1. Update loader CSS. 
2. Functions stored in global.js. 
3. Inactive background for English papers.
=> Add: loader in all papers.

src/Components/Blogs/Blog1.js, src/Components/Blogs/Blog2.js, src/Components/Blogs/Blog3.js, src/Components/Blogs/Blog4.js, src/Components/Blogs/Blog5.js, src/Components/Blogs/Blog6.js
1. Updated navbar changes in blogs pages.
=> Update: navbar in blogs pages.

src/Components/Blogs.js, src/Components/Blogs/Blog1.js, src/Components/Blogs/Blog2.js, src/Components/Blogs/Blog3.js, src/Components/Blogs/Blog4.js, src/Components/Blogs/Blog5.js, src/Components/Blogs/Blog6.js, src/Components/Homepage.js, src/Components/Navbar.js, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
1. Update styling of Navbar in each page.
2. Add basic responsiveness in navbar.
=> Update: Basic styling for navbar completed.

src/Components/Exploremore.js, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
1. Correct slight CSS for Explore more options.
2. Update render functionality to each question paper.
=> Update: Render effect applied to each and every page.

src/Components/Navbar.js, src/assets/style.css
1. mostly pages responsive
2. need to work more on responsive 
3. huburger icon fix when screen is lower tha 640
=> add: humburger icon when screen is on md or lower

src/App.js, src/Components/Body.js, src/Components/Exploremore.js, src/Components/Footer.js, src/Components/Loader.js, src/Papers/HindiHalfpapers.js
1. Added 10th-ssc in the end of question papers' URL.
2. Add loader CSS of disable background.
=> Update: URL changes for question papers, Loader CSS styling

src/Components/Blogs.js, src/Components/Loginpage.js
1. Blogs page responsiveness
2. Login page responsiveness
3. Login page update in Button and layout
=> :update in blogs and login page

src/Components/Footer.js, src/Components/Navbar.js, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
1. Add: redirection to home
2. Resolve: solution button click handle.
=> Add: redirection to home;Resolve: solution button click handle.

src/App.js, src/Components/Blogs.js, src/Components/Loginpage.js, src/Components/Navbar.js
1. Change the url to lowercase for blogs and login page
2. Update in placeholder of login page for sign up and sign in
=> :Update in Url and Login page

src/Components/Blogs/Blog1.js, src/Components/Blogs/Blog2.js, src/Components/ContactUs.js, src/Components/Loginpage.js
1.Update in css of Login and contact us page.
=> :Update in ContactUs and Login page

src/Components/Blogs.js, src/Components/Breadcrumbs.js, src/Components/ContactUs.js, src/Components/ContactUsLink.js, src/Components/Loginpage.js
1. Responsive for contact us page.
2. login page update
3. Responsive for blogs page.
=> :Update in contact us  ,blogs and loginpage

src/Components/LoginComponent.js, src/Components/StaticTag.js, src/Papers/Historypapers.js
1. Add static tag
2. Update in Loginpage
3. Add logincomponent page
=> :Add Static tag

src/Components/AboutUs.js, src/Components/Blogs.js, src/Components/ContactUs.js, src/Components/Homepage.js, src/Components/Loginpage.js, src/Components/StaticTag.js, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
1. Added static tags in all pages .
=> :Static tag in all pages

src/Components/Blogs.js, src/Components/LoginComponent.js
1. Add pagination in blogs page
2. css change in sign in
=> :add pagination and update in sign in

src/Components/Exploremore.js, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
1. Make explore more page responsive.
2. Change background of loader to black(Couldn't make transparent yet.)
3. Basic responsiveness in question papers(Not completed yet).
=> Update: Make explore more page responsive

src/Components/Exploremore.js, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
1. Make all the question papers responsive.
=> Update: make question paper pages responsive.

src/Components/Exploremore.js, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
1. Correct the margin of all question papers blocks.
2. Correct explore more heading margin.
=> Update: correct the margin of question papers.

src/Components/Blogs.js, src/Components/LoginComponent.js
1. Update in css of LoginPage
2. Pagination update
=> :Upadate in Loginpage and blogs page

src/Components/Breadcrumbs.js, src/Components/Footer.js, src/Components/QuestionAnswer.js
1. Aligned the home breadcrumb with navlogo
2. Round edge for QuestionsAnswers
3. Update in Footer and its css
=> :update in Footer

src/Components/Body.js, src/Components/ConfigData.js, src/Components/Exploremore.js, src/Components/Footer.js, src/Components/LoginComponent.js
1. Add global config data file.
2. Remove all instances of config API.
3. Add functionality to read through config data file.
=> Add: Config data

src/App.js, src/Components/Footer.js, src/Components/Privacy&Policy.js, src/Components/Terms&Conditions.js
1. Add Terms and conditions page
2. Add privacy policy page
3. Footer update
=> :Terms and Conditions

src/Components/LoginComponent.js, src/Components/Privacy&Policy.js, src/Components/Terms&Conditions.js
1. Update in terms and condition page
2. update in privacy  and policy page
3. responsive of sign in for mobile size
=> :Add Terms and Privacy

src/Components/LoginComponent.js, src/Components/Privacy&Policy.js, src/Components/Terms&Conditions.js
1. update in css of terms and conditons
2. validation for sign up form
=> :update in sign up

src/Components/LoginComponent.js, src/Components/Privacy&Policy.js, src/Components/Terms&Conditions.js
1. validation for password, email and phone no. in sign up
2. humberger css in terms and policy page update
=> :change in css of Login,TnC

src/Components/Fetchdata.js, src/Components/Navbar.js, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
1. Add functionality to check login and logout state before opening question paper and solution.
2. Basic fixes.
=> Add: Open que paper based on login state functionality.

src/Components/Breadcrumbs.js, src/Components/LoginComponent.js, src/Components/Privacy&Policy.js, src/Components/Terms&Conditions.js, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
1. Update in css for breadcrumb in all pages and papers
2. heading change in terms and conditions and privacy and policy
3. Login page css update
=> :update breadcrumb css

src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
Add LocalStorage functionality to all question papers.
=> Add: Localstorage functionality to all que_papers.

src/Components/LoginComponent.js
1. solve the issue for login /signin
2. update css in input fields
=> :Cleared issue for login

src/Components/Footer.js, src/Components/LoginComponent.js
1. Given values for the select role .
2. Different value for fieldd of SignUp and SignIn for Password 
3. Footer css for screen width 1024
=> :LoginPage and Footer update

package-lock.json, src/Components/LoginComponent.js, src/Components/Navbar.js, src/Components/StaticTag.js
=> Cleared login logout

src/Components/Contentscreen.js, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
1. Add zoom in functionality in mobile view.
2. Make the pdf viewer responsive.
=> Add: Zoomin and zoomout feature for mobile.

package-lock.json, package.json, src/Components/Footer.js, src/Components/LoginComponent.js
1. clear issue of hover for footer
2. add eye icon for signin/signup password field
=> :clear issue for footer

src/Components/Footer.js, src/Components/LoginComponent.js
1. Add prefix 91 to phone no.
2. footer css responsive for mobile phone
=> :prefix 91 in login

src/Components/LoginComponent.js
1.Update the error message in signin for invalid credentials
=> :Error message

src/Components/StaticTag.js, src/assets/style.css
1. Remove border for static tag in all pages 
2. Change in css for navbar components while hover
=> :Remove border for static tag

src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
1. Add coming soon button when there is no solution URL.
=> Add: Coming soon button

src/Components/Body.js, src/Components/Contentscreen.js, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
1. Make API URL dynamic.
2. Change color for Coming soon button.
3. Make coming soon button a block element.
=> Update: make medium dynamic in url, Css changes

src/Components/LoginComponent.js
1. add 91 to input field when user enters numeric value and when email, 91 is not added , when submitted and api is called .
=> :91 testing for signin

src/Components/Body.js
1. Make medium field as required attribute.
2. Do Basic login checks (Everything looks fine).
=> Update: Mark medium field as required.

src/Components/Body.js, src/Components/LoginComponent.js, src/Components/Navbar.js, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
=> Fix: fetch isuue.

package-lock.json, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
1. The question papers tabs were not in center on big screens, this has been fixed in this PR.
=> Fix: responsiveness on big screens.

src/Components/Body.js, src/Components/Footer.js, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
1. Add default medium as Marathi when no medium is selected.
2. Question paper data will be fetched each time.
=> Fix: rediretion bug, question-paper fetching bug.

src/Components/LoginComponent.js
Hamburger menu visible when scrolled up in mobile view
=> Hamburger menu visible

src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
Add Helmet tag to all question papers except Math1 as it was already done with title description branch.
=> Add: Helmet tag to all question papers.

src/Components/AboutUs.js, src/Components/Blogs.js, src/Components/Blogs/Blog1.js, src/Components/Blogs/Blog2.js, src/Components/Blogs/Blog3.js, src/Components/Blogs/Blog4.js, src/Components/Blogs/Blog5.js, src/Components/Blogs/Blog6.js, src/Components/ContactUs.js, src/Components/Homepage.js, src/Components/Loginpage.js, src/Papers/Englishpapers.js, src/Papers/Geographypapers.js, src/Papers/HindiFullpapers.js, src/Papers/HindiHalfpapers.js, src/Papers/Historypapers.js, src/Papers/Marathipapers.js, src/Papers/Math1papers.js, src/Papers/Math2papers.js, src/Papers/SanskritFullpapers.js, src/Papers/SanskritHalfpapers.js, src/Papers/Science1.js, src/Papers/Science2.js
1. Add canonical tags in each question paper. 
2. Add canonical tag for login-page. 
3. Add canonical tag for homepage. 
4. Add canonical tag for blogs-page
5. Add canonical tag for about-us-page.
6. Add canonical tag for contact-us-page.
=> Seo patch canonical for all pages

src/Components/AboutUs.js, src/Components/Blogs/Blog1.js, src/Components/Blogs/Blog2.js, src/Components/Blogs/Blog3.js, src/Components/Blogs/Blog4.js, src/Components/Blogs/Blog5.js, src/Components/Blogs/Blog6.js, src/Components/ContactUs.js, src/Components/Homepage.js
Add meta title and meta description in contact us page.
Add meta title and meta description in about us page.
Add meta title and meta description in homepage.
Add meta title and meta description in blog1, blog2 upto blog6 pages.
=> Add: Meta title and meta description in contact us, about us, homepage and all blogs pages.

src/App.js, src/Components/Blogs.js, src/Components/Blogs/Blog10.js, src/Components/Blogs/Blog7.js, src/Components/Blogs/Blog8.js, src/Components/Blogs/Blog9.js
=> added new blogs
